### ISSUE TITLE
New App Checklist

### ISSUE THREAD

**Issue by ormsbee** [openedx/openedx-learning#230]
Need to write a doc of things so we don't forget. Should mention

- [ ] import linter
- [ ] model conventions
- [ ] private API conventions
- [ ] public API conventions
- [ ] preferred way to make tests
- [ ] places where we deviate from OEP-49 (particularly how we pass around querysets)
- [ ] philosophy on small apps that encapsulate discrete pieces of functionality
- [ ] philosophy on extensible models
- [ ] boundaries we want to enforce (e.g. leaving authorization out)

(other folks please feel free to add stuff)
